name: Sphinx-furo deployment

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-24.04
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: false
          cache: true
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
